trigger:
- main

resources:
- repo: self

variables:
  dockerRegistryServiceConnection: 'test1'
  imageRepository: 'wirexia0/cloud-computing-lab'
  containerRegistry: 'docker.io'
  dockerfilePath: '**/Dockerfile'
  tag: 'latest'
  imagePullSecret: 'labo5test5269-auth'
  vmImageName: 'ubuntu-latest'
  kubernetesServiceConnection: 'cluster_conn'

stages:
- stage: CI
  displayName: CI stage
  jobs:
  - job: Build
    displayName: Build
    pool:
      name: 'Self-hosted-pool'
    steps:
    - task: Docker@2
      displayName: Build and push an image to container registry
      inputs:
        command: buildAndPush
        repository: $(imageRepository)
        dockerfile: $(dockerfilePath)
        containerRegistry: $(dockerRegistryServiceConnection)
        tags: |
          $(tag)

    - upload: manifests
      artifact: manifests

- stage: CD
  displayName: CD stage
  dependsOn: CI

  jobs:
  - deployment: Deploy
    displayName: Deploy
    pool:
      name: 'Self-hosted-pool'
    environment: 'self-hosted'
    strategy:
      runOnce:
        deploy:
          steps:
          - task: KubernetesManifest@0
            displayName: Create imagePullSecret
            inputs:
              action: createSecret
              secretName: $(imagePullSecret)
              dockerRegistryEndpoint: $(dockerRegistryServiceConnection)
              kubernetesServiceConnection: $(kubernetesServiceConnection)

          - task: KubernetesManifest@0
            displayName: Deploy to Kubernetes cluster
            inputs:
              action: deploy
              kubernetesServiceConnection: $(kubernetesServiceConnection)
              manifests: |
                $(Pipeline.Workspace)/manifests/deployment.yml
                $(Pipeline.Workspace)/manifests/service.yml
              imagePullSecrets: |
                $(imagePullSecret)
              containers: |
                $(containerRegistry)/$(imageRepository):$(tag)

