apiVersion : apps/v1
kind: Deployment
metadata:
  name: cloud-computing-lab 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloud-computing-lab
  template:
    metadata:
      labels:
        app: cloud-computing-lab 
    spec:
      containers:
        - name: cloud-computing-lab 
          image: cclab5containerregistry.azurecr.io/cloud-computing-lab
          ports:
          - containerPort: 80
