apiVersion: v1
kind: Service
metadata:
    name: cloud-computing-lab
spec:
    type: LoadBalancer
    loadBalancerIP: 20.90.226.192
    ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 3000
    selector:
        app: cloud-computing-lab
