apiVersion: v1
kind: Service
metadata:
    name: cloud-computing-lab
spec:
    type: LoadBalancer
    loadBalancerIP: 20.26.167.145
    ports:
    - protocol: TCP 
    port: 80 
    targetPort: 80
    selector:
        app: cloud-computing-lab
